import '@tams-ui/components/base/style'
import '@tams-ui/components/input/style'
import '@tams-ui/components/button/style'
import '@tams-ui/components/checkbox/style'
import '@tams-ui/components/checkbox-group/style'
import '@tams-ui/theme-chalk/src/transfer.scss'
