import '@tams-ui/components/base/style/css'
import '@tams-ui/components/input/style/css'
import '@tams-ui/components/tag/style/css'
import '@tams-ui/components/scrollbar/style/css'
import '@tams-ui/components/popper/style/css'
import '@tams-ui/components/virtual-list/style/css'
import '@tams-ui/theme-chalk/el-select-v2.css'
