import '@tams-ui/components/base/style'
import '@tams-ui/components/input/style'
import '@tams-ui/components/tag/style'
import '@tams-ui/components/scrollbar/style'
import '@tams-ui/components/popper/style'
import '@tams-ui/components/virtual-list/style'
import '@tams-ui/theme-chalk/src/select-v2.scss'
